using System.Collections.Generic;

namespace BreathCasino.Gameplay
{
    public static class BCLocalization
    {
        private const string FallbackLanguage = "EN";

        private static readonly Dictionary<string, Dictionary<string, string>> Table = new()
        {
            ["EN"] = BuildEnglish(),
            ["RU"] = BuildRussian(),
            ["UK"] = BuildUkrainian(),
            ["PT"] = BuildPortuguese(),
            ["PL"] = BuildPolish()
        };

        public static string CurrentLanguageCode { get; private set; } = FallbackLanguage;

        public static void SetLanguage(string languageCode)
        {
            CurrentLanguageCode = string.IsNullOrWhiteSpace(languageCode)
                ? FallbackLanguage
                : languageCode.ToUpperInvariant();
        }

        public static string Get(string key)
        {
            if (string.IsNullOrWhiteSpace(key))
            {
                return string.Empty;
            }

            if (TryGet(CurrentLanguageCode, key, out string value))
            {
                return value;
            }

            if (TryGet(FallbackLanguage, key, out value))
            {
                return value;
            }

            return key;
        }

        public static string LocalizeRuntimeText(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                return string.Empty;
            }

            return text switch
            {
                "Quick Setup ready." => Get("runtime.quick_setup_ready"),
                "Player took the round card stack." => Get("runtime.player_took_round_stack"),
                "Lever hold skip only works while defending." => Get("runtime.lever_skip_defense_only"),
                "Player skipped the defense by pulling the lever." => Get("runtime.player_skipped_defense"),
                "Tickets are now used through the lever and shelf interaction." => Get("runtime.tickets_lever_shelf"),
                "Enemy tickets are now driven by enemy lever logic." => Get("runtime.enemy_tickets_lever_logic"),
                "Tickets are disabled in round 1." => Get("runtime.tickets_disabled_round1"),
                "Enemy dialogue test triggered." => Get("runtime.enemy_dialogue_test"),
                "Player hit haze test triggered." => Get("runtime.player_haze_test"),
                "Gun re-docked on the mechanism." => Get("runtime.gun_redocked"),
                "Player ticket shelf toggle requested." => Get("runtime.player_ticket_toggle"),
                "Enemy ticket shelf toggle requested." => Get("runtime.enemy_ticket_toggle"),
                "Player took the issued items from the mechanism." => Get("runtime.player_took_issued_items"),
                "Threat attacks can only be paired with a special card." => Get("runtime.threat_special_only"),
                "Defense is too weak. Cards returned to hand." => Get("runtime.defense_too_weak"),
                "Player skipped the card phase." => Get("runtime.player_skipped_card_phase"),
                "Select a card first, then click a slot." => Get("runtime.select_card_then_slot"),
                "Place a normal card first, then play a special card." => Get("runtime.place_normal_then_special"),
                "Defense: only Resource cards allowed." => Get("runtime.defense_only_resource"),
                "Special cards prohibited this mini-round." => Get("runtime.specials_prohibited"),
                "Attack phase..." => Get("runtime.attack_phase"),
                "Defense phase..." => Get("runtime.defense_phase"),
                "Duel tied. Cards discarded." => Get("runtime.duel_tied"),
                "Click the gun to pick it up. SPACE also picks it up." => Get("runtime.click_gun_pickup"),
                "Gun picked up. RMB = toggle target (self/opponent). SPACE or click gun to shoot." => Get("runtime.gun_picked_up"),
                "Click your issued cards or ticket on the mechanism. SPACE also works." => Get("runtime.click_issued_items"),
                "Ticket shelf opened. Click a ticket, then pull the lever again to retract." => Get("runtime.ticket_shelf_opened"),
                "Enemy used a ticket from the shelf." => Get("runtime.enemy_used_ticket"),
                "Ticket shelf retracted." => Get("runtime.ticket_shelf_retracted"),
                "Player triggered last breath after lethal damage." => Get("runtime.last_breath_triggered"),
                "Player was defeated." => Get("runtime.player_defeated"),
                "Pending player items taken." => Get("runtime.pending_items_taken"),
                "No pending player items." => Get("runtime.no_pending_items"),
                "No ticket action is available right now." => Get("runtime.no_ticket_action"),
                "Tickets only unlock from round 2." => Get("runtime.tickets_round2_unlock"),
                _ => text
            };
        }

        private static bool TryGet(string languageCode, string key, out string value)
        {
            value = null;
            if (!Table.TryGetValue(languageCode, out Dictionary<string, string> map))
            {
                return false;
            }

            return map.TryGetValue(key, out value);
        }

        private static Dictionary<string, string> BuildEnglish()
        {
            return new Dictionary<string, string>
            {
                ["hud.title"] = "Breath Casino Debug",
                ["hud.mode"] = "Mode",
                ["hud.phase"] = "Phase",
                ["hud.round"] = "Round",
                ["hud.mini_round"] = "Mini-round",
                ["hud.player_hp"] = "Player HP",
                ["hud.enemy_hp"] = "Enemy HP",
                ["hud.oxygen"] = "Oxygen",
                ["hud.chamber"] = "Chamber",
                ["hud.player_tickets"] = "Player tickets",
                ["hud.enemy_tickets"] = "Enemy tickets",
                ["hud.last_event"] = "Last event",
                ["hud.validation"] = "Validation issues detected.",

                ["debug.title"] = "Quick Debug",
                ["debug.toggle_help"] = "[F1] Toggle debug help",
                ["debug.restart"] = "[R] Restart match",
                ["debug.round2"] = "[F2] Jump to round 2",
                ["debug.round3"] = "[F3] Jump to round 3",
                ["debug.ticket_player"] = "[T] Give player ticket",
                ["debug.ticket_enemy"] = "[Y] Give enemy ticket",
                ["debug.mechanism"] = "[M] Toggle mechanism",
                ["debug.ticket_player_toggle"] = "[O] Toggle player ticket shelf",
                ["debug.ticket_enemy_toggle"] = "[I] Toggle enemy ticket shelf",
                ["debug.dialogue"] = "[H] Test enemy dialogue",
                ["debug.damage"] = "[J] Test hit haze",
                ["debug.gun"] = "[G] Re-dock gun on mechanism",
                ["debug.pickup"] = "[P] Take pending player items",

                ["menu.title"] = "Breath Casino",
                ["menu.start"] = "Start",
                ["menu.overview"] = "Overview",
                ["menu.overview.title"] = "Overview",
                ["menu.settings"] = "Settings",
                ["menu.settings.title"] = "Settings",
                ["menu.settings.dynamic"] = "Dynamic lighting",
                ["menu.settings.resolution"] = "Resolution",
                ["menu.settings.display"] = "Display mode",
                ["menu.credits"] = "Credits",
                ["menu.credits.title"] = "Credits",
                ["menu.exit"] = "Exit",
                ["menu.exit.title"] = "Leave the table?",
                ["menu.exit.confirm"] = "Close Breath Casino now?",
                ["menu.yes"] = "Yes",
                ["menu.no"] = "No",

                ["screen.fullscreen_window"] = "Borderless fullscreen",
                ["screen.windowed"] = "Windowed",
                ["screen.exclusive_fullscreen"] = "Exclusive fullscreen",

                ["toggle.enabled"] = "Enabled",
                ["toggle.disabled"] = "Disabled",

                ["tooltip.lever.open"] = "<b>Lever</b>\n\nClick to open ticket access.",
                ["tooltip.lever.retract"] = "<b>Lever</b>\n\nClick to retract the shelf.",
                ["tooltip.lever.hold_skip"] = "Hold to skip this defense.",
                ["intro.skip"] = "Skip",
                ["intro.lever_hint"] = "<b>Lever</b>\n\nHold to raise the mechanism.",
                ["intro.caption.1"] = "You wake up to a room that already smells used.",
                ["intro.caption.2"] = "Across the table, someone has been waiting longer than you.",
                ["intro.caption.3"] = "He speaks first, like this place belongs to him.",
                ["intro.caption.4"] = "Listen now. Breathing later gets harder.",
                ["intro.caption.5"] = "When the lights come back, the game begins.",

                ["dialog.enemy.intro.opening.1"] = "Good. Eyes open. That saves me half the work.",
                ["dialog.enemy.intro.opening.2"] = "You are awake, I am still here, and that counts as a decent start.",
                ["dialog.enemy.intro.bullets.1"] = "Those are the rounds. Blank, live, and bad manners in metal form.",
                ["dialog.enemy.intro.bullets.2"] = "You read them fast, or you improvise while bleeding. Two valid schools.",
                ["dialog.enemy.intro.lever.1"] = "Now hold that lever and wake the mechanism properly.",
                ["dialog.enemy.intro.lever.2"] = "Do not be shy. Grip the lever and lift the table's bad habits.",
                ["dialog.enemy.phase_attack.1"] = "Your move.",
                ["dialog.enemy.phase_attack.2"] = "Show me what you kept.",
                ["dialog.enemy.phase_defense.1"] = "Defend yourself.",
                ["dialog.enemy.phase_defense.2"] = "Try not to embarrass your lungs.",
                ["dialog.enemy.player_open_ticket.1"] = "Using tricks now?",
                ["dialog.enemy.player_open_ticket.2"] = "Ah, we are shopping under pressure.",
                ["dialog.enemy.enemy_use_ticket.1"] = "I will take that edge.",
                ["dialog.enemy.enemy_use_ticket.2"] = "House privilege. Do not take it personally.",
                ["dialog.enemy.player_last_breath.1"] = "Still breathing?",
                ["dialog.enemy.player_last_breath.2"] = "Stubborn. I can respect stubborn.",
                ["dialog.enemy.round_start.1"] = "Another round.",
                ["dialog.enemy.round_start.2"] = "Back to the table.",
                ["dialog.enemy.game_over.1"] = "It is finished.",
                ["dialog.enemy.game_over.2"] = "The table keeps its favorite.",
                ["dialog.enemy.post_shot_reflection.1"] = "Pain teaches faster than rules.",
                ["dialog.enemy.post_shot_reflection.2"] = "You see? The room always asks for payment.",
                ["dialog.enemy.post_shot_reflection.3"] = "Nobody likes the lesson, but everybody remembers it.",
                ["dialog.enemy.post_shot_reflection.4"] = "That is the sound of the table correcting a mistake.",
                ["dialog.enemy.post_shot_reflection.5"] = "Keep breathing. You will need the practice.",

                ["runtime.quick_setup_ready"] = "Quick Setup ready.",
                ["runtime.player_took_round_stack"] = "Player took the round card stack.",
                ["runtime.lever_skip_defense_only"] = "Lever hold skip only works while defending.",
                ["runtime.player_skipped_defense"] = "Player skipped the defense by pulling the lever.",
                ["runtime.tickets_lever_shelf"] = "Tickets are now used through the lever and shelf interaction.",
                ["runtime.enemy_tickets_lever_logic"] = "Enemy tickets are now driven by enemy lever logic.",
                ["runtime.tickets_disabled_round1"] = "Tickets are disabled in round 1.",
                ["runtime.enemy_dialogue_test"] = "Enemy dialogue test triggered.",
                ["runtime.player_haze_test"] = "Player hit haze test triggered.",
                ["runtime.gun_redocked"] = "Gun re-docked on the mechanism.",
                ["runtime.player_ticket_toggle"] = "Player ticket shelf toggle requested.",
                ["runtime.enemy_ticket_toggle"] = "Enemy ticket shelf toggle requested.",
                ["runtime.player_took_issued_items"] = "Player took the issued items from the mechanism.",
                ["runtime.threat_special_only"] = "Threat attacks can only be paired with a special card.",
                ["runtime.defense_too_weak"] = "Defense is too weak. Cards returned to hand.",
                ["runtime.player_skipped_card_phase"] = "Player skipped the card phase.",
                ["runtime.select_card_then_slot"] = "Select a card first, then click a slot.",
                ["runtime.place_normal_then_special"] = "Place a normal card first, then play a special card.",
                ["runtime.defense_only_resource"] = "Defense: only Resource cards allowed.",
                ["runtime.specials_prohibited"] = "Special cards prohibited this mini-round.",
                ["runtime.attack_phase"] = "Attack phase...",
                ["runtime.defense_phase"] = "Defense phase...",
                ["runtime.duel_tied"] = "Duel tied. Cards discarded.",
                ["runtime.click_gun_pickup"] = "Click the gun to pick it up. SPACE also picks it up.",
                ["runtime.gun_picked_up"] = "Gun picked up. RMB = toggle target (self/opponent). SPACE or click gun to shoot.",
                ["runtime.click_issued_items"] = "Click your issued cards or ticket on the mechanism. SPACE also works.",
                ["runtime.ticket_shelf_opened"] = "Ticket shelf opened. Click a ticket, then pull the lever again to retract.",
                ["runtime.enemy_used_ticket"] = "Enemy used a ticket from the shelf.",
                ["runtime.ticket_shelf_retracted"] = "Ticket shelf retracted.",
                ["runtime.last_breath_triggered"] = "Player triggered last breath after lethal damage.",
                ["runtime.player_defeated"] = "Player was defeated.",
                ["runtime.pending_items_taken"] = "Pending player items taken.",
                ["runtime.no_pending_items"] = "No pending player items.",
                ["runtime.no_ticket_action"] = "No ticket action is available right now.",
                ["runtime.tickets_round2_unlock"] = "Tickets only unlock from round 2."
            };
        }

        private static Dictionary<string, string> BuildRussian()
        {
            return new Dictionary<string, string>
            {
                ["hud.title"] = "Breath Casino Debug",
                ["hud.mode"] = "Режим",
                ["hud.phase"] = "Фаза",
                ["hud.round"] = "Раунд",
                ["hud.mini_round"] = "Мини-раунд",
                ["hud.player_hp"] = "HP игрока",
                ["hud.enemy_hp"] = "HP противника",
                ["hud.oxygen"] = "Кислород",
                ["hud.chamber"] = "Барабан",
                ["hud.player_tickets"] = "Билеты игрока",
                ["hud.enemy_tickets"] = "Билеты противника",
                ["hud.last_event"] = "Последнее событие",
                ["hud.validation"] = "Обнаружены проблемы валидации.",

                ["debug.title"] = "Быстрый дебаг",
                ["debug.toggle_help"] = "[F1] Переключить дебаг-подсказку",
                ["debug.restart"] = "[R] Перезапустить матч",
                ["debug.round2"] = "[F2] Перейти к раунду 2",
                ["debug.round3"] = "[F3] Перейти к раунду 3",
                ["debug.ticket_player"] = "[T] Дать билет игроку",
                ["debug.ticket_enemy"] = "[Y] Дать билет противнику",
                ["debug.mechanism"] = "[M] Переключить механизм",
                ["debug.ticket_player_toggle"] = "[O] Переключить полку билетов игрока",
                ["debug.ticket_enemy_toggle"] = "[I] Переключить полку билетов противника",
                ["debug.dialogue"] = "[H] Проверить реплику противника",
                ["debug.damage"] = "[J] Проверить эффект попадания",
                ["debug.gun"] = "[G] Вернуть пистолет на механизм",
                ["debug.pickup"] = "[P] Забрать ожидающие предметы игрока",

                ["menu.title"] = "Breath Casino",
                ["menu.start"] = "Начать",
                ["menu.overview"] = "Обзор",
                ["menu.overview.title"] = "Обзор",
                ["menu.settings"] = "Настройки",
                ["menu.settings.title"] = "Настройки",
                ["menu.settings.dynamic"] = "Динамический свет",
                ["menu.settings.resolution"] = "Разрешение",
                ["menu.settings.display"] = "Режим экрана",
                ["menu.credits"] = "Титры",
                ["menu.credits.title"] = "Титры",
                ["menu.exit"] = "Выход",
                ["menu.exit.title"] = "Покинуть стол?",
                ["menu.exit.confirm"] = "Закрыть Breath Casino сейчас?",
                ["menu.yes"] = "Да",
                ["menu.no"] = "Нет",

                ["screen.fullscreen_window"] = "Полноэкранное окно",
                ["screen.windowed"] = "Окно",
                ["screen.exclusive_fullscreen"] = "Эксклюзивный полный экран",

                ["toggle.enabled"] = "Включено",
                ["toggle.disabled"] = "Выключено",

                ["tooltip.lever.open"] = "<b>Рычаг</b>\n\nНажми, чтобы открыть доступ к билетам.",
                ["tooltip.lever.retract"] = "<b>Рычаг</b>\n\nНажми, чтобы убрать полку обратно.",
                ["tooltip.lever.hold_skip"] = "Удерживай, чтобы пропустить эту защиту.",
                ["intro.skip"] = "Пропустить",
                ["intro.lever_hint"] = "<b>Рычаг</b>\n\nЗажми, чтобы поднять механизм.",
                ["intro.caption.1"] = "Ты открываешь глаза в комнате, которая уже кого-то пережила.",
                ["intro.caption.2"] = "Напротив сидит противник. Похоже, он ждал дольше тебя.",
                ["intro.caption.3"] = "Говорить он начинает первым, будто всё это принадлежит ему.",
                ["intro.caption.4"] = "Слушай сейчас. Потом дышать будет сложнее.",
                ["intro.caption.5"] = "Когда свет вернется, игра уже начнется.",

                ["dialog.enemy.intro.opening.1"] = "Хорошо. Глаза открылись. Уже облегчил мне работу.",
                ["dialog.enemy.intro.opening.2"] = "Ты проснулся, я всё ещё здесь. Для начала этого вполне достаточно.",
                ["dialog.enemy.intro.bullets.1"] = "Вот патроны. Холостые, боевые и плохие манеры в металлическом корпусе.",
                ["dialog.enemy.intro.bullets.2"] = "Запоминай быстро. Второй способ обучения тут заметно болезненнее.",
                ["dialog.enemy.intro.lever.1"] = "Теперь зажми рычаг и подними механизм как положено.",
                ["dialog.enemy.intro.lever.2"] = "Не стесняйся. Схвати рычаг и разбуди стол окончательно.",
                ["dialog.enemy.phase_attack.1"] = "Твой ход.",
                ["dialog.enemy.phase_attack.2"] = "Покажи, что у тебя осталось.",
                ["dialog.enemy.phase_defense.1"] = "Защищайся.",
                ["dialog.enemy.phase_defense.2"] = "Постарайся не опозорить свои легкие.",
                ["dialog.enemy.player_open_ticket.1"] = "Пошел за трюками?",
                ["dialog.enemy.player_open_ticket.2"] = "А, начинаем закупаться под давлением.",
                ["dialog.enemy.enemy_use_ticket.1"] = "Это преимущество я заберу себе.",
                ["dialog.enemy.enemy_use_ticket.2"] = "Привилегия заведения. Ничего личного.",
                ["dialog.enemy.player_last_breath.1"] = "Все еще дышишь?",
                ["dialog.enemy.player_last_breath.2"] = "Упрямо. Такое я уважаю.",
                ["dialog.enemy.round_start.1"] = "Еще раунд.",
                ["dialog.enemy.round_start.2"] = "Снова к столу.",
                ["dialog.enemy.game_over.1"] = "На этом всё.",
                ["dialog.enemy.game_over.2"] = "Стол выбрал любимчика.",
                ["dialog.enemy.post_shot_reflection.1"] = "Боль объясняет правила быстрее слов.",
                ["dialog.enemy.post_shot_reflection.2"] = "Видишь? Эта комната всегда берет оплату.",
                ["dialog.enemy.post_shot_reflection.3"] = "Никому не нравится урок, но все его помнят.",
                ["dialog.enemy.post_shot_reflection.4"] = "Это стол исправляет чужую ошибку.",
                ["dialog.enemy.post_shot_reflection.5"] = "Дыши дальше. Тренировка тебе понадобится.",

                ["runtime.quick_setup_ready"] = "Быстрая настройка готова.",
                ["runtime.player_took_round_stack"] = "Игрок забрал стопку карт раунда.",
                ["runtime.lever_skip_defense_only"] = "Удержание рычага для пропуска работает только в защите.",
                ["runtime.player_skipped_defense"] = "Игрок пропустил защиту, потянув рычаг.",
                ["runtime.tickets_lever_shelf"] = "Билеты теперь используются через рычаг и полку.",
                ["runtime.enemy_tickets_lever_logic"] = "Билеты противника теперь зависят от логики его рычага.",
                ["runtime.tickets_disabled_round1"] = "В первом раунде билеты отключены.",
                ["runtime.enemy_dialogue_test"] = "Тест реплики противника запущен.",
                ["runtime.player_haze_test"] = "Тест эффекта попадания по игроку запущен.",
                ["runtime.gun_redocked"] = "Пистолет снова установлен на механизм.",
                ["runtime.player_ticket_toggle"] = "Запрошено переключение полки билетов игрока.",
                ["runtime.enemy_ticket_toggle"] = "Запрошено переключение полки билетов противника.",
                ["runtime.player_took_issued_items"] = "Игрок забрал выданные предметы с механизма.",
                ["runtime.threat_special_only"] = "Threat-атака может идти только вместе со спецкартой.",
                ["runtime.defense_too_weak"] = "Защита слишком слабая. Карты возвращены в руку.",
                ["runtime.player_skipped_card_phase"] = "Игрок пропустил карточную фазу.",
                ["runtime.select_card_then_slot"] = "Сначала выбери карту, затем нажми на слот.",
                ["runtime.place_normal_then_special"] = "Сначала положи обычную карту, затем играй спецкарту.",
                ["runtime.defense_only_resource"] = "Защита: доступны только карты Resource.",
                ["runtime.specials_prohibited"] = "Спецкарты запрещены в этом мини-раунде.",
                ["runtime.attack_phase"] = "Фаза атаки...",
                ["runtime.defense_phase"] = "Фаза защиты...",
                ["runtime.duel_tied"] = "Дуэль вничью. Карты сброшены.",
                ["runtime.click_gun_pickup"] = "Нажми на пистолет, чтобы взять его. SPACE тоже работает.",
                ["runtime.gun_picked_up"] = "Пистолет взят. RMB = сменить цель. SPACE или клик по пистолету, чтобы выстрелить.",
                ["runtime.click_issued_items"] = "Нажми на выданные карты или билет на механизме. SPACE тоже работает.",
                ["runtime.ticket_shelf_opened"] = "Полка билетов открыта. Нажми билет, затем снова потяни рычаг, чтобы убрать полку.",
                ["runtime.enemy_used_ticket"] = "Противник использовал билет с полки.",
                ["runtime.ticket_shelf_retracted"] = "Полка билетов убрана.",
                ["runtime.last_breath_triggered"] = "Игрок включил последнюю попытку после смертельного урона.",
                ["runtime.player_defeated"] = "Игрок побежден.",
                ["runtime.pending_items_taken"] = "Ожидающие предметы игрока забраны.",
                ["runtime.no_pending_items"] = "У игрока нет ожидающих предметов.",
                ["runtime.no_ticket_action"] = "Сейчас для билетов нет доступного действия.",
                ["runtime.tickets_round2_unlock"] = "Билеты открываются только со второго раунда."
            };
        }

        private static Dictionary<string, string> BuildUkrainian()
        {
            return new Dictionary<string, string>
            {
                ["hud.title"] = "Breath Casino Debug",
                ["hud.mode"] = "Режим",
                ["hud.phase"] = "Фаза",
                ["hud.round"] = "Раунд",
                ["hud.mini_round"] = "Міні-раунд",
                ["hud.player_hp"] = "HP гравця",
                ["hud.enemy_hp"] = "HP противника",
                ["hud.oxygen"] = "Кисень",
                ["hud.chamber"] = "Барабан",
                ["hud.player_tickets"] = "Квитки гравця",
                ["hud.enemy_tickets"] = "Квитки противника",
                ["hud.last_event"] = "Остання подія",
                ["hud.validation"] = "Виявлено проблеми валідації.",

                ["debug.title"] = "Швидкий дебаг",
                ["debug.toggle_help"] = "[F1] Перемкнути дебаг-підказку",
                ["debug.restart"] = "[R] Перезапустити матч",
                ["debug.round2"] = "[F2] Перейти до раунду 2",
                ["debug.round3"] = "[F3] Перейти до раунду 3",
                ["debug.ticket_player"] = "[T] Дати квиток гравцю",
                ["debug.ticket_enemy"] = "[Y] Дати квиток противнику",
                ["debug.mechanism"] = "[M] Перемкнути механізм",
                ["debug.ticket_player_toggle"] = "[O] Перемкнути полицю квитків гравця",
                ["debug.ticket_enemy_toggle"] = "[I] Перемкнути полицю квитків противника",
                ["debug.dialogue"] = "[H] Перевірити репліку противника",
                ["debug.damage"] = "[J] Перевірити ефект влучання",
                ["debug.gun"] = "[G] Повернути пістолет на механізм",
                ["debug.pickup"] = "[P] Забрати очікуючі предмети гравця",

                ["menu.title"] = "Breath Casino",
                ["menu.start"] = "Почати",
                ["menu.overview"] = "Огляд",
                ["menu.overview.title"] = "Огляд",
                ["menu.settings"] = "Налаштування",
                ["menu.settings.title"] = "Налаштування",
                ["menu.settings.dynamic"] = "Динамічне світло",
                ["menu.settings.resolution"] = "Роздільна здатність",
                ["menu.settings.display"] = "Режим екрана",
                ["menu.credits"] = "Титри",
                ["menu.credits.title"] = "Титри",
                ["menu.exit"] = "Вихід",
                ["menu.exit.title"] = "Покинути стіл?",
                ["menu.exit.confirm"] = "Закрити Breath Casino зараз?",
                ["menu.yes"] = "Так",
                ["menu.no"] = "Ні",

                ["screen.fullscreen_window"] = "Повноекранне вікно",
                ["screen.windowed"] = "Вікно",
                ["screen.exclusive_fullscreen"] = "Ексклюзивний повний екран",

                ["toggle.enabled"] = "Увімкнено",
                ["toggle.disabled"] = "Вимкнено",

                ["tooltip.lever.open"] = "<b>Важіль</b>\n\nНатисни, щоб відкрити доступ до квитків.",
                ["tooltip.lever.retract"] = "<b>Важіль</b>\n\nНатисни, щоб сховати полицю назад.",
                ["tooltip.lever.hold_skip"] = "Утримуй, щоб пропустити цей захист.",
                ["intro.skip"] = "Пропустити",
                ["intro.lever_hint"] = "<b>Важіль</b>\n\nЗатисни, щоб підняти механізм.",
                ["intro.caption.1"] = "Ти відкриваєш очі в кімнаті, яка вже когось пережила.",
                ["intro.caption.2"] = "Навпроти сидить противник. Схоже, він чекав довше за тебе.",
                ["intro.caption.3"] = "Говорити він починає першим, наче все це належить йому.",
                ["intro.caption.4"] = "Слухай зараз. Потім дихати буде складніше.",
                ["intro.caption.5"] = "Коли світло повернеться, гра вже піде далі.",

                ["dialog.enemy.intro.opening.1"] = "Добре. Очі відкрились. Уже полегшив мені роботу.",
                ["dialog.enemy.intro.opening.2"] = "Ти прокинувся, я все ще тут. Для початку цього досить.",
                ["dialog.enemy.intro.bullets.1"] = "Ось патрони. Холості, бойові й погані манери в металевій оболонці.",
                ["dialog.enemy.intro.bullets.2"] = "Запам'ятовуй швидко. Другий спосіб навчання тут болючіший.",
                ["dialog.enemy.intro.lever.1"] = "Тепер затисни важіль і підніми механізм як слід.",
                ["dialog.enemy.intro.lever.2"] = "Не соромся. Схопи важіль і добряче розбуди цей стіл.",
                ["dialog.enemy.phase_attack.1"] = "Твій хід.",
                ["dialog.enemy.phase_attack.2"] = "Покажи, що в тебе залишилося.",
                ["dialog.enemy.phase_defense.1"] = "Захищайся.",
                ["dialog.enemy.phase_defense.2"] = "Спробуй не осоромити власні легені.",
                ["dialog.enemy.player_open_ticket.1"] = "Пішов по хитрощі?",
                ["dialog.enemy.player_open_ticket.2"] = "Ага, закупівля під тиском.",
                ["dialog.enemy.enemy_use_ticket.1"] = "Цю перевагу я заберу собі.",
                ["dialog.enemy.enemy_use_ticket.2"] = "Привілей закладу. Нічого особистого.",
                ["dialog.enemy.player_last_breath.1"] = "Все ще дихаєш?",
                ["dialog.enemy.player_last_breath.2"] = "Вперто. Таке я поважаю.",
                ["dialog.enemy.round_start.1"] = "Ще раунд.",
                ["dialog.enemy.round_start.2"] = "Знову до столу.",
                ["dialog.enemy.game_over.1"] = "На цьому все.",
                ["dialog.enemy.game_over.2"] = "Стіл обрав улюбленця.",
                ["dialog.enemy.post_shot_reflection.1"] = "Біль пояснює правила швидше за слова.",
                ["dialog.enemy.post_shot_reflection.2"] = "Бачиш? Ця кімната завжди бере оплату.",
                ["dialog.enemy.post_shot_reflection.3"] = "Нікому не подобається урок, але всі його пам'ятають.",
                ["dialog.enemy.post_shot_reflection.4"] = "Це стіл виправляє чужу помилку.",
                ["dialog.enemy.post_shot_reflection.5"] = "Дихай далі. Тренування ще знадобиться.",

                ["runtime.quick_setup_ready"] = "Швидке налаштування готове.",
                ["runtime.player_took_round_stack"] = "Гравець забрав стос карт раунду.",
                ["runtime.lever_skip_defense_only"] = "Утримання важеля для пропуску працює лише в захисті.",
                ["runtime.player_skipped_defense"] = "Гравець пропустив захист, потягнувши важіль.",
                ["runtime.tickets_lever_shelf"] = "Квитки тепер використовуються через важіль і полицю.",
                ["runtime.enemy_tickets_lever_logic"] = "Квитки противника тепер залежать від логіки його важеля.",
                ["runtime.tickets_disabled_round1"] = "У першому раунді квитки вимкнені.",
                ["runtime.enemy_dialogue_test"] = "Тест репліки противника запущено.",
                ["runtime.player_haze_test"] = "Тест ефекту влучання по гравцю запущено.",
                ["runtime.gun_redocked"] = "Пістолет знову встановлено на механізм.",
                ["runtime.player_ticket_toggle"] = "Запитано перемикання полиці квитків гравця.",
                ["runtime.enemy_ticket_toggle"] = "Запитано перемикання полиці квитків противника.",
                ["runtime.player_took_issued_items"] = "Гравець забрав видані предмети з механізму.",
                ["runtime.threat_special_only"] = "Threat-атака може йти лише разом зі спецкартою.",
                ["runtime.defense_too_weak"] = "Захист надто слабкий. Карти повернено в руку.",
                ["runtime.player_skipped_card_phase"] = "Гравець пропустив карткову фазу.",
                ["runtime.select_card_then_slot"] = "Спочатку вибери карту, потім натисни на слот.",
                ["runtime.place_normal_then_special"] = "Спочатку поклади звичайну карту, потім грай спецкарту.",
                ["runtime.defense_only_resource"] = "Захист: доступні лише карти Resource.",
                ["runtime.specials_prohibited"] = "Спецкарти заборонені в цьому міні-раунді.",
                ["runtime.attack_phase"] = "Фаза атаки...",
                ["runtime.defense_phase"] = "Фаза захисту...",
                ["runtime.duel_tied"] = "Дуель внічию. Карти скинуто.",
                ["runtime.click_gun_pickup"] = "Натисни на пістолет, щоб взяти його. SPACE теж працює.",
                ["runtime.gun_picked_up"] = "Пістолет узято. RMB = змінити ціль. SPACE або клік по пістолету, щоб вистрілити.",
                ["runtime.click_issued_items"] = "Натисни на видані карти або квиток на механізмі. SPACE теж працює.",
                ["runtime.ticket_shelf_opened"] = "Полиця квитків відкрита. Натисни квиток, потім знову потягни важіль, щоб сховати полицю.",
                ["runtime.enemy_used_ticket"] = "Противник використав квиток з полиці.",
                ["runtime.ticket_shelf_retracted"] = "Полицю квитків сховано.",
                ["runtime.last_breath_triggered"] = "Гравець увімкнув останню спробу після смертельної шкоди.",
                ["runtime.player_defeated"] = "Гравця переможено.",
                ["runtime.pending_items_taken"] = "Очікуючі предмети гравця забрано.",
                ["runtime.no_pending_items"] = "У гравця немає очікуючих предметів.",
                ["runtime.no_ticket_action"] = "Зараз для квитків немає доступної дії.",
                ["runtime.tickets_round2_unlock"] = "Квитки відкриваються лише з другого раунду."
            };
        }

        private static Dictionary<string, string> BuildPortuguese()
        {
            return new Dictionary<string, string>
            {
                ["hud.title"] = "Breath Casino Debug",
                ["hud.mode"] = "Modo",
                ["hud.phase"] = "Fase",
                ["hud.round"] = "Ronda",
                ["hud.mini_round"] = "Mini-ronda",
                ["hud.player_hp"] = "HP do jogador",
                ["hud.enemy_hp"] = "HP do inimigo",
                ["hud.oxygen"] = "Oxigenio",
                ["hud.chamber"] = "Tambor",
                ["hud.player_tickets"] = "Bilhetes do jogador",
                ["hud.enemy_tickets"] = "Bilhetes do inimigo",
                ["hud.last_event"] = "Ultimo evento",
                ["hud.validation"] = "Foram encontrados problemas de validacao.",

                ["debug.title"] = "Debug Rapido",
                ["debug.toggle_help"] = "[F1] Alternar ajuda de debug",
                ["debug.restart"] = "[R] Reiniciar partida",
                ["debug.round2"] = "[F2] Ir para a ronda 2",
                ["debug.round3"] = "[F3] Ir para a ronda 3",
                ["debug.ticket_player"] = "[T] Dar bilhete ao jogador",
                ["debug.ticket_enemy"] = "[Y] Dar bilhete ao inimigo",
                ["debug.mechanism"] = "[M] Alternar mecanismo",
                ["debug.ticket_player_toggle"] = "[O] Alternar prateleira de bilhetes do jogador",
                ["debug.ticket_enemy_toggle"] = "[I] Alternar prateleira de bilhetes do inimigo",
                ["debug.dialogue"] = "[H] Testar dialogo do inimigo",
                ["debug.damage"] = "[J] Testar nevoa de impacto",
                ["debug.gun"] = "[G] Reencaixar arma no mecanismo",
                ["debug.pickup"] = "[P] Recolher itens pendentes do jogador",

                ["menu.title"] = "Breath Casino",
                ["menu.start"] = "Iniciar",
                ["menu.overview"] = "Visao geral",
                ["menu.overview.title"] = "Visao geral",
                ["menu.settings"] = "Definicoes",
                ["menu.settings.title"] = "Definicoes",
                ["menu.settings.dynamic"] = "Iluminacao dinamica",
                ["menu.settings.resolution"] = "Resolucao",
                ["menu.settings.display"] = "Modo de ecran",
                ["menu.credits"] = "Creditos",
                ["menu.credits.title"] = "Creditos",
                ["menu.exit"] = "Sair",
                ["menu.exit.title"] = "Sair da mesa?",
                ["menu.exit.confirm"] = "Fechar Breath Casino agora?",
                ["menu.yes"] = "Sim",
                ["menu.no"] = "Nao",

                ["screen.fullscreen_window"] = "Ecran inteiro sem moldura",
                ["screen.windowed"] = "Janela",
                ["screen.exclusive_fullscreen"] = "Ecran inteiro exclusivo",

                ["toggle.enabled"] = "Ativado",
                ["toggle.disabled"] = "Desativado",

                ["tooltip.lever.open"] = "<b>Alavanca</b>\n\nClica para abrir o acesso aos bilhetes.",
                ["tooltip.lever.retract"] = "<b>Alavanca</b>\n\nClica para recolher a prateleira.",
                ["tooltip.lever.hold_skip"] = "Segura para saltar esta defesa.",
                ["intro.skip"] = "Saltar",
                ["intro.lever_hint"] = "<b>Alavanca</b>\n\nSegura para levantar o mecanismo.",
                ["intro.caption.1"] = "Acordas numa sala que ja mastigou outras pessoas.",
                ["intro.caption.2"] = "Do outro lado da mesa, o inimigo espera ha mais tempo do que tu.",
                ["intro.caption.3"] = "Ele fala primeiro, como se este lugar lhe pertencesse.",
                ["intro.caption.4"] = "Ouve agora. Respirar depois vai custar mais.",
                ["intro.caption.5"] = "Quando a luz voltar, o jogo ja comecou.",

                ["dialog.enemy.intro.opening.1"] = "Boa. Abriste os olhos. Ja me poupaste trabalho.",
                ["dialog.enemy.intro.opening.2"] = "Tu acordaste, eu continuo aqui. Para ja, chega.",
                ["dialog.enemy.intro.bullets.1"] = "Essas sao as municoes. Vazias, vivas e mal educadas em metal.",
                ["dialog.enemy.intro.bullets.2"] = "Memoriza depressa. A segunda forma de aprender doi mais.",
                ["dialog.enemy.intro.lever.1"] = "Agora segura essa alavanca e levanta o mecanismo como deve ser.",
                ["dialog.enemy.intro.lever.2"] = "Sem vergonha. Agarra a alavanca e acorda a mesa de vez.",
                ["dialog.enemy.phase_attack.1"] = "A tua vez.",
                ["dialog.enemy.phase_attack.2"] = "Mostra o que guardaste.",
                ["dialog.enemy.phase_defense.1"] = "Defende-te.",
                ["dialog.enemy.phase_defense.2"] = "Tenta nao envergonhar os teus pulmoes.",
                ["dialog.enemy.player_open_ticket.1"] = "Ja vais aos truques?",
                ["dialog.enemy.player_open_ticket.2"] = "Compras sob pressao. Classico.",
                ["dialog.enemy.enemy_use_ticket.1"] = "Fico com essa vantagem.",
                ["dialog.enemy.enemy_use_ticket.2"] = "Privilegio da casa. Nada pessoal.",
                ["dialog.enemy.player_last_breath.1"] = "Ainda respiras?",
                ["dialog.enemy.player_last_breath.2"] = "Teimoso. Respeito isso.",
                ["dialog.enemy.round_start.1"] = "Mais uma ronda.",
                ["dialog.enemy.round_start.2"] = "De volta a mesa.",
                ["dialog.enemy.game_over.1"] = "Acabou.",
                ["dialog.enemy.game_over.2"] = "A mesa ficou com o favorito.",
                ["dialog.enemy.post_shot_reflection.1"] = "A dor ensina mais depressa do que as regras.",
                ["dialog.enemy.post_shot_reflection.2"] = "Ves? Esta sala cobra sempre.",
                ["dialog.enemy.post_shot_reflection.3"] = "Ninguem gosta da licao, mas toda a gente se lembra.",
                ["dialog.enemy.post_shot_reflection.4"] = "Esse e o som da mesa a corrigir um erro.",
                ["dialog.enemy.post_shot_reflection.5"] = "Continua a respirar. Vais precisar de pratica.",

                ["runtime.quick_setup_ready"] = "Configuracao rapida pronta.",
                ["runtime.player_took_round_stack"] = "O jogador apanhou a pilha de cartas da ronda.",
                ["runtime.lever_skip_defense_only"] = "Segurar a alavanca para saltar so funciona na defesa.",
                ["runtime.player_skipped_defense"] = "O jogador saltou a defesa ao puxar a alavanca.",
                ["runtime.tickets_lever_shelf"] = "Os bilhetes agora usam a alavanca e a prateleira.",
                ["runtime.enemy_tickets_lever_logic"] = "Os bilhetes do inimigo agora dependem da logica da alavanca dele.",
                ["runtime.tickets_disabled_round1"] = "Os bilhetes estao desativados na ronda 1.",
                ["runtime.enemy_dialogue_test"] = "Teste de dialogo do inimigo iniciado.",
                ["runtime.player_haze_test"] = "Teste de nevoa de impacto do jogador iniciado.",
                ["runtime.gun_redocked"] = "Arma recolocada no mecanismo.",
                ["runtime.player_ticket_toggle"] = "Pedido para alternar a prateleira de bilhetes do jogador.",
                ["runtime.enemy_ticket_toggle"] = "Pedido para alternar a prateleira de bilhetes do inimigo.",
                ["runtime.player_took_issued_items"] = "O jogador recolheu os itens entregues pelo mecanismo.",
                ["runtime.threat_special_only"] = "Ataques Threat so podem ser combinados com uma carta especial.",
                ["runtime.defense_too_weak"] = "A defesa e demasiado fraca. As cartas voltaram para a mao.",
                ["runtime.player_skipped_card_phase"] = "O jogador saltou a fase de cartas.",
                ["runtime.select_card_then_slot"] = "Escolhe primeiro uma carta e depois clica num slot.",
                ["runtime.place_normal_then_special"] = "Coloca primeiro uma carta normal e depois joga a especial.",
                ["runtime.defense_only_resource"] = "Defesa: so cartas Resource sao permitidas.",
                ["runtime.specials_prohibited"] = "Cartas especiais proibidas nesta mini-ronda.",
                ["runtime.attack_phase"] = "Fase de ataque...",
                ["runtime.defense_phase"] = "Fase de defesa...",
                ["runtime.duel_tied"] = "Duelo empatado. Cartas descartadas.",
                ["runtime.click_gun_pickup"] = "Clica na arma para a apanhar. SPACE tambem funciona.",
                ["runtime.gun_picked_up"] = "Arma apanhada. RMB = mudar alvo. SPACE ou clique na arma para disparar.",
                ["runtime.click_issued_items"] = "Clica nas cartas entregues ou no bilhete no mecanismo. SPACE tambem funciona.",
                ["runtime.ticket_shelf_opened"] = "Prateleira de bilhetes aberta. Clica num bilhete e depois puxa a alavanca outra vez para recolher.",
                ["runtime.enemy_used_ticket"] = "O inimigo usou um bilhete da prateleira.",
                ["runtime.ticket_shelf_retracted"] = "Prateleira de bilhetes recolhida.",
                ["runtime.last_breath_triggered"] = "O jogador ativou o ultimo folego apos dano letal.",
                ["runtime.player_defeated"] = "O jogador foi derrotado.",
                ["runtime.pending_items_taken"] = "Itens pendentes do jogador recolhidos.",
                ["runtime.no_pending_items"] = "Nao ha itens pendentes do jogador.",
                ["runtime.no_ticket_action"] = "Nao ha nenhuma acao de bilhete disponivel agora.",
                ["runtime.tickets_round2_unlock"] = "Os bilhetes so desbloqueiam a partir da ronda 2."
            };
        }

        private static Dictionary<string, string> BuildPolish()
        {
            return new Dictionary<string, string>
            {
                ["hud.title"] = "Breath Casino Debug",
                ["hud.mode"] = "Tryb",
                ["hud.phase"] = "Faza",
                ["hud.round"] = "Runda",
                ["hud.mini_round"] = "Mini-runda",
                ["hud.player_hp"] = "HP gracza",
                ["hud.enemy_hp"] = "HP przeciwnika",
                ["hud.oxygen"] = "Tlen",
                ["hud.chamber"] = "Beben",
                ["hud.player_tickets"] = "Bilety gracza",
                ["hud.enemy_tickets"] = "Bilety przeciwnika",
                ["hud.last_event"] = "Ostatnie zdarzenie",
                ["hud.validation"] = "Wykryto problemy walidacji.",

                ["debug.title"] = "Szybki Debug",
                ["debug.toggle_help"] = "[F1] Przelacz pomoc debug",
                ["debug.restart"] = "[R] Restart meczu",
                ["debug.round2"] = "[F2] Skok do rundy 2",
                ["debug.round3"] = "[F3] Skok do rundy 3",
                ["debug.ticket_player"] = "[T] Daj bilet graczowi",
                ["debug.ticket_enemy"] = "[Y] Daj bilet przeciwnikowi",
                ["debug.mechanism"] = "[M] Przelacz mechanizm",
                ["debug.ticket_player_toggle"] = "[O] Przelacz polke biletow gracza",
                ["debug.ticket_enemy_toggle"] = "[I] Przelacz polke biletow przeciwnika",
                ["debug.dialogue"] = "[H] Test dialogu przeciwnika",
                ["debug.damage"] = "[J] Test mgly trafienia",
                ["debug.gun"] = "[G] Zadokuj bron na mechanizmie",
                ["debug.pickup"] = "[P] Odbierz oczekujace przedmioty gracza",

                ["menu.title"] = "Breath Casino",
                ["menu.start"] = "Start",
                ["menu.overview"] = "Przeglad",
                ["menu.overview.title"] = "Przeglad",
                ["menu.settings"] = "Ustawienia",
                ["menu.settings.title"] = "Ustawienia",
                ["menu.settings.dynamic"] = "Dynamiczne oswietlenie",
                ["menu.settings.resolution"] = "Rozdzielczosc",
                ["menu.settings.display"] = "Tryb ekranu",
                ["menu.credits"] = "Tworcy",
                ["menu.credits.title"] = "Tworcy",
                ["menu.exit"] = "Wyjscie",
                ["menu.exit.title"] = "Opuscic stol?",
                ["menu.exit.confirm"] = "Zamknac Breath Casino teraz?",
                ["menu.yes"] = "Tak",
                ["menu.no"] = "Nie",

                ["screen.fullscreen_window"] = "Pelen ekran bez ramek",
                ["screen.windowed"] = "Okno",
                ["screen.exclusive_fullscreen"] = "Ekskluzywny pelny ekran",

                ["toggle.enabled"] = "Wlaczone",
                ["toggle.disabled"] = "Wylaczone",

                ["tooltip.lever.open"] = "<b>Dzwignia</b>\n\nKliknij, aby otworzyc dostep do biletow.",
                ["tooltip.lever.retract"] = "<b>Dzwignia</b>\n\nKliknij, aby schowac polke.",
                ["tooltip.lever.hold_skip"] = "Przytrzymaj, aby pominac te obrone.",
                ["intro.skip"] = "Pomin",
                ["intro.lever_hint"] = "<b>Dzwignia</b>\n\nPrzytrzymaj, aby podniesc mechanizm.",
                ["intro.caption.1"] = "Budzi cie pokoj, ktory juz przez kogos przeszedl.",
                ["intro.caption.2"] = "Po drugiej stronie stolu siedzi przeciwnik. Czeka dluzej niz ty.",
                ["intro.caption.3"] = "Odzywa sie pierwszy, jakby to miejsce nalezalo do niego.",
                ["intro.caption.4"] = "Sluchaj teraz. Potem oddychanie bedzie drozsze.",
                ["intro.caption.5"] = "Gdy swiatlo wroci, gra juz ruszyla.",

                ["dialog.enemy.intro.opening.1"] = "Dobrze. Oczy otwarte. Oszczedziles mi pracy.",
                ["dialog.enemy.intro.opening.2"] = "Ty sie obudziles, ja nadal tu jestem. Na poczatek wystarczy.",
                ["dialog.enemy.intro.bullets.1"] = "To naboje. Slepe, ostre i bardzo niemile w metalowej skorze.",
                ["dialog.enemy.intro.bullets.2"] = "Zapamietaj szybko. Drugi sposob nauki boli bardziej.",
                ["dialog.enemy.intro.lever.1"] = "Teraz przytrzymaj dzwignie i podnies mechanizm jak nalezy.",
                ["dialog.enemy.intro.lever.2"] = "Bez wstydu. Zlap dzwignie i obudz stol do konca.",
                ["dialog.enemy.phase_attack.1"] = "Twoj ruch.",
                ["dialog.enemy.phase_attack.2"] = "Pokaz, co jeszcze masz.",
                ["dialog.enemy.phase_defense.1"] = "Bron sie.",
                ["dialog.enemy.phase_defense.2"] = "Sprobuj nie skompromitowac swoich pluc.",
                ["dialog.enemy.player_open_ticket.1"] = "Siegasz po sztuczki?",
                ["dialog.enemy.player_open_ticket.2"] = "Zakupy pod presja. Ladnie.",
                ["dialog.enemy.enemy_use_ticket.1"] = "Biore te przewage.",
                ["dialog.enemy.enemy_use_ticket.2"] = "Przywilej lokalu. Nic osobistego.",
                ["dialog.enemy.player_last_breath.1"] = "Wciaz oddychasz?",
                ["dialog.enemy.player_last_breath.2"] = "Uparty. To szanuje.",
                ["dialog.enemy.round_start.1"] = "Jeszcze jedna runda.",
                ["dialog.enemy.round_start.2"] = "Wracamy do stolu.",
                ["dialog.enemy.game_over.1"] = "To koniec.",
                ["dialog.enemy.game_over.2"] = "Stol zatrzymal ulubienca.",
                ["dialog.enemy.post_shot_reflection.1"] = "Bol uczy szybciej niz zasady.",
                ["dialog.enemy.post_shot_reflection.2"] = "Widzisz? Ten pokoj zawsze pobiera oplaty.",
                ["dialog.enemy.post_shot_reflection.3"] = "Nikt nie lubi tej lekcji, ale wszyscy ja pamietaja.",
                ["dialog.enemy.post_shot_reflection.4"] = "To stol poprawia czyjs blad.",
                ["dialog.enemy.post_shot_reflection.5"] = "Oddychaj dalej. Przyda ci sie trening.",

                ["runtime.quick_setup_ready"] = "Szybka konfiguracja gotowa.",
                ["runtime.player_took_round_stack"] = "Gracz zabral stos kart rundy.",
                ["runtime.lever_skip_defense_only"] = "Przytrzymanie dzwigni do pomijania dziala tylko w obronie.",
                ["runtime.player_skipped_defense"] = "Gracz pominol obrone, pociagajac za dzwignie.",
                ["runtime.tickets_lever_shelf"] = "Bilety sa teraz uzywane przez dzwignie i polke.",
                ["runtime.enemy_tickets_lever_logic"] = "Bilety przeciwnika zalezne sa teraz od logiki jego dzwigni.",
                ["runtime.tickets_disabled_round1"] = "W rundzie 1 bilety sa wylaczone.",
                ["runtime.enemy_dialogue_test"] = "Uruchomiono test dialogu przeciwnika.",
                ["runtime.player_haze_test"] = "Uruchomiono test efektu trafienia gracza.",
                ["runtime.gun_redocked"] = "Bron ponownie zadokowana na mechanizmie.",
                ["runtime.player_ticket_toggle"] = "Zadano przelaczenie polki biletow gracza.",
                ["runtime.enemy_ticket_toggle"] = "Zadano przelaczenie polki biletow przeciwnika.",
                ["runtime.player_took_issued_items"] = "Gracz odebral przedmioty wydane przez mechanizm.",
                ["runtime.threat_special_only"] = "Atak Threat mozna laczyc tylko z karta specjalna.",
                ["runtime.defense_too_weak"] = "Obrona jest za slaba. Karty wrocily do reki.",
                ["runtime.player_skipped_card_phase"] = "Gracz pominol faze kart.",
                ["runtime.select_card_then_slot"] = "Najpierw wybierz karte, potem kliknij slot.",
                ["runtime.place_normal_then_special"] = "Najpierw poloz zwykla karte, potem zagraj specjalna.",
                ["runtime.defense_only_resource"] = "Obrona: dozwolone sa tylko karty Resource.",
                ["runtime.specials_prohibited"] = "Karty specjalne sa zabronione w tej mini-rundzie.",
                ["runtime.attack_phase"] = "Faza ataku...",
                ["runtime.defense_phase"] = "Faza obrony...",
                ["runtime.duel_tied"] = "Remis pojedynku. Karty odrzucone.",
                ["runtime.click_gun_pickup"] = "Kliknij bron, aby ja podniesc. SPACE tez dziala.",
                ["runtime.gun_picked_up"] = "Bron podniesiona. RMB = zmiana celu. SPACE lub klikniecie broni, aby strzelic.",
                ["runtime.click_issued_items"] = "Kliknij wydane karty lub bilet na mechanizmie. SPACE tez dziala.",
                ["runtime.ticket_shelf_opened"] = "Polka biletow otwarta. Kliknij bilet, potem ponownie pociagnij dzwignie, aby schowac polke.",
                ["runtime.enemy_used_ticket"] = "Przeciwnik uzyl biletu z polki.",
                ["runtime.ticket_shelf_retracted"] = "Polka biletow schowana.",
                ["runtime.last_breath_triggered"] = "Gracz uruchomil ostatni oddech po smiertelnym obrazeniu.",
                ["runtime.player_defeated"] = "Gracz zostal pokonany.",
                ["runtime.pending_items_taken"] = "Odebrano oczekujace przedmioty gracza.",
                ["runtime.no_pending_items"] = "Brak oczekujacych przedmiotow gracza.",
                ["runtime.no_ticket_action"] = "Brak dostepnej akcji biletowej w tej chwili.",
                ["runtime.tickets_round2_unlock"] = "Bilety odblokowuja sie dopiero od rundy 2."
            };
        }
    }
}
