using UnityEditor;
using UnityEngine;

namespace BreathCasino.EditorTools
{
    /// <summary>
    /// Архивный helper для legacy blockout-сцены.
    /// Оставлен только как исторический маркер пайплайна.
    /// </summary>
    public static class SetupHelper
    {
        [MenuItem("Breath Casino/Archive/Blockout/Setup Helper/Validate and Fix Scene")]
        public static void ValidateAndFixScene()
        {
            Debug.Log("Legacy blockout setup helper is archived. Use 'Breath Casino/Main Scene/Rebuild mainScene' for the active workflow.");
        }

        [MenuItem("Breath Casino/Archive/Blockout/Setup Helper/Create Camera Placeholders")]
        public static void CreateCameraPlaceholders()
        {
            Debug.Log("Legacy blockout camera placeholders are archived. mainScene placeholders are generated by MainSceneBuilder.");
        }
    }
}
